# #############################
#
#
# SecuWear Docker Container
#
#
# #############################

# Pull base image
FROM ubuntu:14.04
FROM python:2.7
# install all files and run makes



#git clone https://github.com/greatscottgadgets/libbtbb.git
#cd libbtbb
#mkdir build
#cd build
#cmake ..
#make
#sudo make install

#git clone https://github.com/greatscottgadgets/ubertooth.git
#cd ubertooth/host
#mkdir build
#cd build
#cmake ..
#make
#sudo make install

