version: "3"
services:
    aggregatorservice:
        image: python:2.7
        build: .
        command: python secuwear_webapp/manage.py migrate --noinput
        command: python secuwear_webapp/manage.py runserver 0.0.0.0:4000
        volumes:
            - .:/code
        ports:
            - "4000:4000"




